name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron:  '0,30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update latest blog
    steps:
      - uses: actions/checkout@v3
      - uses: Bpazy/issue-list-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
