name: Update latest blog

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update latest blog
    steps:
      - uses: actions/checkout@v3
      - uses: Bpazy/issue-list-action@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_NAME: Bpazy
          GITHUB_EMAIL: hanziyuan08@outlook.com
